import "./globals.css";
import { Montserrat } from "next/font/google";
import { Navbar } from "./components/nav";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className="h-screen w-screen relative bg-slate-50 overflow-x-hidden">
          <div
            className="p-3 sm:p-5 md:p-8 lg:p-10 absolute top-0 left-0 w-screen
          h-screen"
          >
            <div className=" border-2 relative h-full w-full border-slate-300 overflow-hidden">
              <div className="absolute top-3 left-3 text-2xl text-slate-600">
                <span>brand</span>
              </div>
              <Navbar />
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
